### PR TITLE
Script converted to GT-MP

### PR DESCRIPTION
**Pull request by MrNeta**
It's already Tested and works fine ;)

Best wishes
Neta

**Discord:** Neta#2575

### CODE REVIEW

**Comment by MissyMelissa** [comment]
Nice! You changed the indentation from tabs to spaces though :(

**Comment by MrNeta** [comment]
oh, didn't see that. I'll fix that :)

**Comment by MrNeta** [comment]
Okay it's done 👍

**Comment by MissyMelissa** [comment]
Thanks! 🎉

**Comment by MrNeta** [comment]
No problem 😄

**Pull request merged**
